general {
    disable_loading_bar = true
    grace = 300
    hide_cursor = true
    no_fade_in = false
}

background {
    monitor =
    path = ~/Documents/wallpaper/wpmountainteal.jpg  # wallpaper
    blur_passes = 4
    contrast = 0.85
    brightness = 0.75
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 220, 55
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgba(ff4b6e 0.85)   
    inner_color = rgba(15, 4, 8, 0.9)  
    font_color = rgb(ffe6ea)           
    fade_on_empty = true
    font_family = JetBrainsMono Nerd Font Mono
    placeholder_text = <span weight='400' color='#b57682'>Enter Password...</span>
    hide_input = false
    position = 0, -110
    halign = center
    valign = center
}

label {
    monitor =
    text = Welcome  # your theme name
    color = rgba(ffe6ea 0.95)
    font_size = 48
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = savara
    color = rgba(ff4b6e 0.95)  # red accent
    font_size = 32
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, 140
    halign = center
    valign = center
}
